version: '3'

services:
  server:
    build: ./server
    container_name: fastapi_server
    ports:
      - "8000:8000"  
    networks:
      - app_network

  app:
    build: ./app
    container_name: streamlit_app
    ports:
      - "8501:8501"  
    depends_on:
      - server
    networks:
      - app_network
    environment:
      - API_URL=http://fastapi_server:8000 

networks:
  app_network:
    driver: bridge
